### ISSUE TITLE
FRENSIE installing compiling error.How can i solve this problem Ubuntu22.04

### ISSUE THREAD

**Issue by emilmammadzada99** [FRENSIE/FRENSIE#228]
emil@DESKTOP-:~/FRENSIE-pub/build$ ./frensie.sh
cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR test_exec_monitor)
  (Required is at least version "1.72.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindBoost.cmake:2360 (find_package_handle_standard_args)
  cmake/EnableBoostSupport.cmake:23 (FIND_PACKAGE)
  CMakeLists.txt:170 (ENABLE_BOOST_SUPPORT)

-- Configuring incomplete, errors occurred!
See also "/home/emil/FRENSIE-pub/build/CMakeFiles/CMakeOutput.log".

**Comment by lewisgross1296** [comment]
Hi @emillon779 the development of FRENSIE has not been active for a while, so in order to get it to install, you'd likely need much older version of Ubuntu. I'm pretty sure I have it working on Ubuntu 18.04, so I'd recommend trying to build FRENSIE using Docker. Here is a [repo](https://github.com/lewisgross1296/docker_cluster) where I did this. Good luck getting it to build!

FYI there are no current FRENSIE developers, so there's really not a lot of support. If you just want forward Monte Carlo, OpenMC is great, but if you want the adjoint, then it may be worth working with FRENSIE.
